**NumPy:**

Ask Questions?
Why?
Industry Use Case
Materialize Knowledge into Interview Questions

Data Toolkit or Frameworks:
Numpy, Pandas, Seaborn, Matplotlib

To Play with data we have to prepare the data using data toolkit called python library

What is Python Library?
Collection of functions
functions can be reused
It is a optimized function because lot of testing is done on python library

NumPy: Numerical Python Library
Numpy(array) is faster than list
It is a framework where 60-90% it is built on python but Numpy core computation was built on c/c++
It is fast because of array property
It is used in data analysis world.
It is responsible for mathematical operations
There are 10,000 + mathematical functions in numpy
How to achieve fastest mathematical calculations/computations in python?
use numpy

Interview Questions:
1. Which is the fastest programming language?
c++
2. why numpy is faster?
3. why numpy is used in data analysis or data science?
4. if any problem occurs find solution in numpy offical documentation.
5. Why c++ is faster?
Proximity to Hardware:
C++ provides a high level of control over hardware resources, allowing developers to write code that is more closely aligned with the underlying hardware architecture. This proximity to the hardware enables developers to optimize code for specific platforms.

Efficient Abstractions:
C++ supports both high-level abstractions (such as classes and templates) and low-level operations (such as direct memory manipulation). This versatility allows developers to choose the level of abstraction that best suits their performance requirements.

Static Typing:
C++ is a statically-typed language, which means that variable types are known at compile time. This can lead to more efficient code execution as the compiler can make better optimizations knowing the types of variables.

No Garbage Collection:
Unlike some other high-level languages like Java or Python, C++ does not have automatic garbage collection. While this places more responsibility on the programmer for managing memory, it can result in more predictable and efficient memory usage.
6. Why List is used?
List can store hetrogenous elements or different elements

In [3]:
import numpy as np #2005 by Travis Oliphant

In [4]:
np.__version__

'1.26.0'

In [5]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [6]:
#Why numpy
#10k+ mathematical functions
#Faster

In [7]:
l = [1, 2, 3, 4, 5]
arr = np.array(l)
arr

array([1, 2, 3, 4, 5])

In [8]:
type(np.array(l)) #nd means N Dimensions

numpy.ndarray

In [9]:
arr.ndim

1

In [10]:
l = [1, 2, 3, 4, 5, "Rishi"]
arr1 = np.array(l)
arr1

# U11 is a string formats in python library
# U11 is a string type
# Example :
# int32, int64 is number of bits where data is stored
# OS will allocate memory based on string data type that is in python is U11

array(['1', '2', '3', '4', '5', 'Rishi'], dtype='<U11')

In [11]:
type(np.array(l)) #nd means N Dimensions

numpy.ndarray

In [12]:
arr1.ndim

1

In [13]:
arr

array([1, 2, 3, 4, 5])

In [14]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
arr1.ndim

2

In [16]:
l = [1, 2, 3, 4]
np.array(l)
mat = np.matrix(l) #matris will be by default 2d
mat

matrix([[1, 2, 3, 4]])

In [17]:
np.matrix([[[1, 2], [5, 6], [7, 8]]])
# matrix is a sub class of array, better use array
# matrix has a restriction cannot support more than 2D

ValueError: matrix must be 2-dimensional

In [ ]:
np.array([[[1, 2], [5, 6], [7, 8]]])

array([[[1, 2],
        [5, 6],
        [7, 8]]])

In [ ]:
#more way to convert to array
np.asarray([[[1, 2], [5, 6], [7, 8]]])

array([[[1, 2],
        [5, 6],
        [7, 8]]])

In [ ]:
np.asanyarray([[[1, 2], [5, 6], [7, 8]]]) #Convert the input to an ndarray, but pass ndarray subclasses through.

array([[[1, 2],
        [5, 6],
        [7, 8]]])

In [ ]:
mat

matrix([[1, 2, 3, 4]])

In [ ]:
np.asanyarray(mat) 
# matrix pass through array, matrix doesn't convert into array, it just passes the array as it is 
# because matrix is the subclass of an array.
# If list is passed as a parameter np.asanyarray(list) then np.asanyarray will convert into array

matrix([[1, 2, 3, 4]])

In [ ]:
np.asarray([[[1, 2], [5, 6], [7, 8]]]) # convert list into array
# np convert any array into an array, but
# if any array is subclass of an array, np.asarray don't convert into array it just passes the array as it is 

array([[[1, 2],
        [5, 6],
        [7, 8]]])

In [ ]:
np.array([[[1, 2], [5, 6], [7, 8]]]) 

array([[[1, 2],
        [5, 6],
        [7, 8]]])

In [ ]:
tup = ([1,2,3], [4,5,6])
type(tup)

tuple

In [ ]:
np.array(tup)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a=5
np.array(a)

array(5)

In [ ]:
# numpy array previous version it is numpy.asarray()
# numpy array latest version is numpy.array()

# np.asanyarray :
# matrix pass through array, matrix doesn't convert into array, it just passes the array as it is,
# because matrix is the subclass of an array.
# # If list is passed as a parameter np.asanyarray(list) then np.asanyarray will convert into array

In [ ]:
# Shallow copy
# If source array is changed and destination array is also changed and points to same memory location
l = [1, 2, 3, 4, 5]
arr = np.array(l)
arr

array([1, 2, 3, 4, 5])

In [ ]:
a = arr
a

array([1, 2, 3, 4, 5])

In [ ]:
a[0] = 1000
a

array([1000,    2,    3,    4,    5])

In [ ]:
arr

array([1000,    2,    3,    4,    5])

In [ ]:
# Deep Copy
# If source array is changed and destination array is doesn't change
#  because it points to different memory location.
a

array([1000,    2,    3,    4,    5])

In [ ]:
b = a.copy()
b[0] = 2000
b

array([2000,    2,    3,    4,    5])

In [ ]:
a

array([1000,    2,    3,    4,    5])

In [ ]:
# arrays, Lists, Dictionaries are mutuable and can do shallow and deep copy operations
# tuple and set are immutable
# set where both shallow_copy_set and deep_copy_set behave the same because sets can only contain immutable elements. 
# The deepcopy function, in this case, effectively performs a shallow copy, and modifying the elements in either set does not affect the original set.

import copy

# Sets
original_set = {1, 2}  # Sets cannot contain mutable elements like lists

# Shallow copy for set (Note: Shallow copy behaves like a copy for sets)
shallow_copy_set = copy.copy(original_set)

# Deep copy for set (Note: Deep copy behaves like a copy for sets, effectively a shallow copy)
deep_copy_set = copy.deepcopy(original_set)

# Modify the set elements in the copies (will raise an error for the set)
shallow_copy_set.add(5)  # No Error
deep_copy_set.add(6)     # No Error

print(original_set)        # Output: {1, 2}
print(shallow_copy_set, original_set)   # Output: {1, 2, 5}
print(deep_copy_set, original_set)      # Output: {1, 2, 6}

{1, 2}
{1, 2, 5} {1, 2}
{1, 2, 6} {1, 2}


In [ ]:
import copy

# Dictionaries
original_dict = {'a': 1, 'b': [2, 3], 'c': 4}

# Shallow copy for dictionary
shallow_copy_dict = copy.copy(original_dict)

# Deep copy for dictionary
deep_copy_dict = copy.deepcopy(original_dict)

# Modify the nested list in the copies
shallow_copy_dict['b'][0] = 'X'
deep_copy_dict['b'][0] = 'Y'

print(original_dict)         # Output: {'a': 1, 'b': ['X', 3], 'c': 4}
print(shallow_copy_dict, original_dict)     # Output: {'a': 1, 'b': ['X', 3], 'c': 4}
print(deep_copy_dict, original_dict)        # Output: {'a': 1, 'b': ['Y', 3], 'c': 4}

{'a': 1, 'b': ['X', 3], 'c': 4}
{'a': 1, 'b': ['X', 3], 'c': 4} {'a': 1, 'b': ['X', 3], 'c': 4}
{'a': 1, 'b': ['Y', 3], 'c': 4} {'a': 1, 'b': ['X', 3], 'c': 4}


In [ ]:
#There are multiple ways to generating arrays

In [ ]:
np.fromfunction(lambda i, j : i==j, (3, 3))
# or
# np.fromfunction(lambda i, j : i==j, shape=(3, 3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [ ]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr1.shape

(2, 3)

In [ ]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr.shape

(5,)

In [ ]:
arr1.size # number of elements

6

In [ ]:
arr.size

5

In [ ]:
np.fromfunction(lambda i, j : i==j, (3, 3)) 
# compare the indices of 3x3 matrix
# i values are x axis or rows 
# j values are y axis or columns
# 00 , 11 , 22

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [ ]:
np.fromfunction(lambda i, j : i*j, (3, 3)) 

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [ ]:
range(5) # it is iterator

range(0, 5)

In [ ]:
for i in range(5):
    print(i)

0
1
2
3
4


In [ ]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [ ]:
list(i for i in range(5))

[0, 1, 2, 3, 4]

In [ ]:
list(range(5))

[0, 1, 2, 3, 4]

In [ ]:
iterable = (i*i for i in range(5))
# (i*i for i in range(5))
# i is called iterator
# generator is a function that generates the number, where
# that number is iterable

In [ ]:
np.fromiter(iterable, int)

array([ 0,  1,  4,  9, 16])

In [ ]:
np.fromstring('23 34 67', sep = ' ')

array([23., 34., 67.])

In [ ]:
np.fromstring('23,34,67', sep = ',')

array([23., 34., 67.])

In [ ]:
np.fromstring('Suhani,Ajay,Anwesha', sep = ',')
# cannot use string because by numpy array default value is considering as float.

# Why numpy array default value is considering as float ?
# when float value 4.3 is converted into integer, the 0.3 value data is lost only 4 is converted

C:\Users\ramki\AppData\Local\Temp\ipykernel_17784\4232903791.py:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring('Suhani,Ajay,Anwesha', sep = ',')


array([], dtype=float64)

In [ ]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr.size

5

In [ ]:
arr.shape

(5,)

In [ ]:
arr.dtype

dtype('int32')

In [ ]:
l = [1, 2,3, "Ajay"] # if one value data type is string or float etc that is added in array
# then whole array is converted into string or float etc
arr = np.array(l)
arr.dtype

dtype('<U11')

In [ ]:
arr # whole array is converted into string

array(['1', '2', '3', 'Ajay'], dtype='<U11')

In [ ]:
list(range(5))

[0, 1, 2, 3, 4]

In [ ]:
range(5)

range(0, 5)

In [ ]:
list(range(1.0, 2.10)) 
#  range cannot deal with float values only deal with int values

# Interview Question:
# 1. Demerits of range function?
# it cannot deal with float values

TypeError: 'float' object cannot be interpreted as an integer

In [ ]:
list(np.arange(0.1, 10.2, 0.1))
# np.arange(0.1, 10.2, 0.1)
# generate the values from 0.1 to 10.2 with jump of 0.1

[0.1,
 0.2,
 0.30000000000000004,
 0.4,
 0.5,
 0.6,
 0.7000000000000001,
 0.8,
 0.9,
 1.0,
 1.1,
 1.2000000000000002,
 1.3000000000000003,
 1.4000000000000001,
 1.5000000000000002,
 1.6,
 1.7000000000000002,
 1.8000000000000003,
 1.9000000000000001,
 2.0,
 2.1,
 2.2,
 2.3000000000000003,
 2.4000000000000004,
 2.5000000000000004,
 2.6,
 2.7,
 2.8000000000000003,
 2.9000000000000004,
 3.0000000000000004,
 3.1,
 3.2,
 3.3000000000000003,
 3.4000000000000004,
 3.5000000000000004,
 3.6,
 3.7,
 3.8000000000000003,
 3.9000000000000004,
 4.0,
 4.1,
 4.2,
 4.3,
 4.3999999999999995,
 4.5,
 4.6,
 4.7,
 4.8,
 4.9,
 5.0,
 5.1,
 5.2,
 5.3,
 5.4,
 5.5,
 5.6,
 5.7,
 5.8,
 5.9,
 6.0,
 6.1,
 6.2,
 6.3,
 6.4,
 6.5,
 6.6,
 6.7,
 6.8,
 6.9,
 7.0,
 7.1,
 7.2,
 7.3,
 7.4,
 7.5,
 7.6,
 7.7,
 7.8,
 7.9,
 8.0,
 8.1,
 8.2,
 8.3,
 8.4,
 8.5,
 8.6,
 8.7,
 8.8,
 8.9,
 9.0,
 9.1,
 9.2,
 9.3,
 9.4,
 9.5,
 9.6,
 9.700000000000001,
 9.8,
 9.9,
 10.0,
 10.1]

In [ ]:
np.linspace(1, 5, 10)
# generate 10 values from 1 to 5 

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [ ]:
np.logspace(1, 5, 10, base = 2)
# generate 10 values of log from 1 to 5 
# Example:
# log 1 base 2, log 2 base 2 ,..., log 5 base 2

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [ ]:
np.logspace(1, 5, 10, base = 10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [ ]:
arr1 = np.zeros(5)
arr1.shape

(5,)

In [ ]:
arr1

array([0., 0., 0., 0., 0.])

In [ ]:
arr1.ndim

1

In [ ]:
arr2 = np.zeros((3, 4))
arr2.shape

(3, 4)

In [ ]:
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr2.ndim

2

In [ ]:
arr3 = np.zeros((3, 3, 4)) # repeat (3,4) for 3 times or in 3 axis
arr3.shape

(3, 3, 4)

In [ ]:
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
arr3.ndim

3

In [ ]:
arr4 = np.zeros((2, 1, 3, 4))  # repeat (3,4) for 1 time or in 1 axis and extra 2 dimension
arr4.shape

(2, 1, 3, 4)

In [ ]:
arr4

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [ ]:
arr4.ndim

4

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
arr = np.ones((3,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [ ]:
arr*3

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [ ]:
# Why are we using np.zeros() or np.ones() ?
# While doing image processing given some features in matrix
# when we don't know the value at given matrix before multiplying

In [ ]:
np.twos((2,3))

AttributeError: module 'numpy' has no attribute 'twos'

In [ ]:
# Interview Questions:
# 1. what is numpy?
# 2. what is array?
# 3. difference between list and array?
# 4. why array is faster than list?
# A: 
# array store homogenous elements and takes less time for retrival
# memory allocation
#  a. list are not stored by themselves
#  b. List uses concept of referencing:
#     Elements in the list are stored at random locations in memory
#     but the address of those random locations are stored in list
#     List uses referencing of all address is called concept of referencing.
# python has garbage collection
#  c. List has concept of resizing: 
#     when size of the list is full adding new element to existing list not possible because of no space
#     python will create big size of list and copy all elements from old list to new list and adds new element to list
#     python will delete old list.

# List has dynamic size or resizing in nature.
# List has to check space and data type when adding elements
# Array doesn't have to check space and data type when adding elements because 
# elements are homogenous and space is static defined in array, that is reason array is faster
# array is statically defined contigous memory allocation and fixed size in nature
# Array and List are mutable

# 1D array : vector
# 2d array : matrix
# 3d array : tensor

# 1. static and dynamic memory allocation affects performance
# 2. datatype
# 3. vectorization :
# when we have rows and columns, treating only columns,
# every column is called vector
# Example:
# when we have 10 lakhs rows and 3 columns then we use vectorization
# because we have less number of columns

# How hetrogenous elements affect the array?
# Answer: Only because of less compactness
# Example:
# arr1=[1,2,3,4]
# arr2=[1,"Ram"] , where 1 is a int and space is 32 bits and "ram" is a string and space is 1 bit
# internally numpy array can't optimize from int to string, that's why compactness affected,
# there is no processing not done fast.

**Numpy Advance**

In [ ]:
import numpy as np
arr = np.ones((3, 4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [ ]:
arr*5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [ ]:
np.empty((3, 4),int) # it will provides random integer values, where float is converted into integer

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
np.eye(3, dtype = int) # diagonal matrix
# n*n matrix
# Example: if n=3 then will provide 3*3 matrix
# use case: image 

# to calculate inverse of matrix we use np.eye()

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#optional

import pandas as pd
pd.DataFrame(arr) # convert array into dataframe

# What is DataFrame?
# It is a multiple rows and multiple columns

0    1    2    3
0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0

In [ ]:
#extra topics
import random
random.choice((1, 2, 3, 4, 5, 6)) # generate a random number

1

In [ ]:
random.choice('Ajay') # generate a character from given string

'A'

In [ ]:
random.randrange(1, 10) # generate a number from 1 to 10

7

In [ ]:
random.random() # any random no is generated between 0 (included), 1 will be excluded

0.7632427841178603

In [ ]:
lis = [1, 2, 3, 4, 5]
random.shuffle(lis)
lis

[2, 5, 4, 3, 1]

In [ ]:
random.uniform(7, 14) # generate number between 7 and 14, from uniform distribution
# distribution is a pattern of data
# machine can only understand numerical values instead of string

9.279515235462588

In [ ]:
np.array([])

array([], dtype=float64)

In [ ]:
np.random.random_sample() # generate a random number

0.6073329730341219

In [ ]:
type(np.random.random_sample())

float

In [ ]:
np.random.random_sample((5,))

array([0.18228335, 0.08304796, 0.0739969 , 0.65201015, 0.36194399])

In [ ]:
np.random.rand(1) # generate random values from given number 0 to 1

array([0.7529296])

In [ ]:
np.random.rand(2, 3) # generate 2x3 random float values

array([[0.6980896 , 0.47425323, 0.16971525],
       [0.53095372, 0.49925202, 0.92636051]])

In [ ]:
np.random.randn(2, 3) # Return a sample (or samples) from the "standard normal" distribution.

array([[-0.31262893, -0.08381358,  1.22319665],
       [-1.26631981, -0.36310478, -1.1043376 ]])

In [ ]:
np.random.random_sample() # Return random floats in the half-open interval [0.0, 1.0)
# half open interval means include 0 exclude 1

0.45138870031490175

In [ ]:
np.random.randint(1, 5, size = (3, 4)) 
# Return random INTEGERS from the "discrete uniform" distribution of the specified dtype in the "half-open" interval [low, high). 
# If high is None (the default), then results are from [0, low).

array([[3, 1, 3, 1],
       [3, 1, 2, 1],
       [1, 4, 3, 2]])

In [ ]:
arr = np.random.randint(1, 5, size = (3, 4))
# generate random integers from 1 to 5 of 3 rows to 4 columns

In [ ]:
arr

array([[2, 1, 3, 3],
       [4, 4, 3, 3],
       [2, 1, 4, 4]])

In [ ]:
arr.size # arr.reshape(2, 1) cannot accomodate 12 elements in 2 rows and 1 column

12

In [ ]:
arr.shape

(3, 4)

In [ ]:
arr.ndim

2

In [ ]:
arr

array([[2, 1, 3, 3],
       [4, 4, 3, 3],
       [2, 1, 4, 4]])

In [ ]:
arr.reshape(2, 6) #array size can not change, multiples of array size
# what is reshape array?
# 

array([[2, 1, 3, 3, 4, 4],
       [3, 3, 2, 1, 4, 4]])

In [ ]:
arr.reshape(6, 2)

array([[2, 1],
       [3, 3],
       [4, 4],
       [3, 3],
       [2, 1],
       [4, 4]])

In [ ]:
arr.reshape(2,6)

array([[2, 1, 3, 3, 4, 4],
       [3, 3, 2, 1, 4, 4]])

In [ ]:
arr.reshape(12,)

array([2, 1, 3, 3, 4, 4, 3, 3, 2, 1, 4, 4])

In [ ]:
arr.reshape(12,1)

array([[2],
       [1],
       [3],
       [3],
       [4],
       [4],
       [3],
       [3],
       [2],
       [1],
       [4],
       [4]])

In [ ]:
arr.reshape(12,2)

ValueError: cannot reshape array of size 12 into shape (12,2)

In [ ]:
arr.reshape(4, 3)

array([[2, 1, 3],
       [3, 4, 4],
       [3, 3, 2],
       [1, 4, 4]])

In [ ]:
arr.reshape(3, 4)

array([[2, 1, 3, 3],
       [4, 4, 3, 3],
       [2, 1, 4, 4]])

In [ ]:
arr

array([[2, 1, 3, 3],
       [4, 4, 3, 3],
       [2, 1, 4, 4]])

In [ ]:
arr.reshape(4, -1)
# know about rows only don't know about how many columns, 
# so mention -1 in second parameter
# if mention -1000 or -1 then -1 is considered

array([[2, 1, 3],
       [3, 4, 4],
       [3, 3, 2],
       [1, 4, 4]])

In [ ]:
arr.reshape(4, -100)
# use case of reshape
# ML model expects the data in different format,
# so reshaping data in this format.

array([[2, 1, 3],
       [3, 4, 4],
       [3, 3, 2],
       [1, 4, 4]])

In [ ]:
arr.reshape(-1, 4)
# don't know about how many rows are there but know about only how many columns are there, 
# so mention -1 in first parameter
# if mention -1000 or -1 then -1 is considered

array([[2, 1, 3, 3],
       [4, 4, 3, 3],
       [2, 1, 4, 4]])

In [ ]:
arr.reshape(-1,-1) # either of rows or columns should be mention
# have to know one dimension atleast

ValueError: can only specify one unknown dimension

In [ ]:
arr.reshape(-1, 5)

ValueError: cannot reshape array of size 12 into shape (5)

In [ ]:
# after reshaping of an array will it be a shallow copy or deep copy?
# shallow copy

# after reshape is it pointing out to same memory location?
# yes

# how to verify?
# use .base after reshape(3,4).base

# what ever dimension is mentioned inside reshape having .base then it gives original array

arr.reshape(3,4).base

array([[2, 1, 3, 3],
       [4, 4, 3, 3],
       [2, 1, 4, 4]])

In [ ]:
arr

array([[2, 1, 3, 3],
       [4, 4, 3, 3],
       [2, 1, 4, 4]])

In [ ]:
arr.reshape(12, ).base

array([[2, 1, 3, 3],
       [4, 4, 3, 3],
       [2, 1, 4, 4]])

In [ ]:
arr

array([[2, 1, 3, 3],
       [4, 4, 3, 3],
       [2, 1, 4, 4]])

In [ ]:
arr.size

12

In [ ]:
arr.reshape(2, 2, 3)
# reshape an 3D array repeated 2 times of 2 rows and 3 columns

array([[[2, 1, 3],
        [3, 4, 4]],

       [[3, 3, 2],
        [1, 4, 4]]])

In [ ]:
arr.reshape(1, 2, 2, 3)
# first parameter is dimension
# reshape an 4D array repeated 2 times of 2 rows and 3 columns

array([[[[2, 1, 3],
         [3, 4, 4]],

        [[3, 3, 2],
         [1, 4, 4]]]])

In [ ]:
arr.reshape(4, 3, 1)

array([[[2],
        [1],
        [3]],

       [[3],
        [4],
        [4]],

       [[3],
        [3],
        [2]],

       [[1],
        [4],
        [4]]])

In [ ]:
arr.reshape(1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 3)

array([[[[[[[[[[[[2, 1, 3],
                 [3, 4, 4]],

                [[3, 3, 2],
                 [1, 4, 4]]]]]]]]]]]])

In [ ]:
lis = [1, 2, 3, 4]
arr = np.array(lis)
arr

array([1, 2, 3, 4])

In [ ]:
arr.ndim

1

In [ ]:
arr2 = np.array([[2, 3], [4, 5]]) # [[]] is 2D array
arr2

array([[2, 3],
       [4, 5]])

In [ ]:
arr2.ndim

2

In [ ]:
arr2 = np.zeros((3, 4))
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr2.ndim

2

In [ ]:
arr3 = np.zeros((1, 3, 4)) # 3 rows, 4 columns >> 2d array + 1d
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
arr3.ndim

3

In [ ]:
arr3.shape

(1, 3, 4)

In [ ]:
arr4 = np.zeros((1, 1, 3, 4)) # 3 rows, 4 columns >> 2d array + 1d +1d
arr4

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [ ]:
arr4.ndim

4

In [ ]:
arr4.shape

(1, 1, 3, 4)

In [ ]:
arr3 = np.zeros((3, 3, 4))
arr3
# first parameter is 3D, where 3 rows and 4 columns are repeated three times

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
arr3.ndim

3

In [ ]:
arr3.shape # 3,4 repeated 3 times in 3D array

(3, 3, 4)

In [ ]:
arr1 = np.random.randint(1, 10, (5, 6))
arr1
# generate random integers from 1 to 10 for 5 rows and 6 columns

array([[8, 9, 4, 1, 9, 7],
       [8, 9, 6, 6, 3, 3],
       [8, 2, 1, 6, 6, 5],
       [8, 1, 7, 4, 4, 2],
       [9, 3, 3, 2, 9, 3]])

In [ ]:
arr1 > 5
# check with index wise element and check condition greater than 5

array([[ True,  True, False, False,  True,  True],
       [ True,  True,  True,  True, False, False],
       [ True, False, False,  True,  True, False],
       [ True, False,  True, False, False, False],
       [ True, False, False, False,  True, False]])

In [ ]:
arr1[arr1 > 5] # need exact values where arr1 > 5 condition is true

array([8, 9, 9, 7, 8, 9, 6, 6, 8, 6, 6, 8, 7, 9, 9])

In [ ]:
arr1[arr1 < 5] # need exact values where arr1 < 5 condition is true

array([4, 1, 3, 3, 2, 1, 1, 4, 4, 2, 3, 3, 2, 3])

In [ ]:
arr1

array([[8, 9, 4, 1, 9, 7],
       [8, 9, 6, 6, 3, 3],
       [8, 2, 1, 6, 6, 5],
       [8, 1, 7, 4, 4, 2],
       [9, 3, 3, 2, 9, 3]])

In [ ]:
arr

array([1, 2, 3, 4])

In [ ]:
# how to access elements?
arr[0]

1

In [ ]:
arr[1]

2

In [ ]:
arr1

array([[8, 9, 4, 1, 9, 7],
       [8, 9, 6, 6, 3, 3],
       [8, 2, 1, 6, 6, 5],
       [8, 1, 7, 4, 4, 2],
       [9, 3, 3, 2, 9, 3]])

In [ ]:
arr1[0:2, [0,2]] #0th - 1st row in continuation and 0th and 2nd column

array([[8, 4],
       [8, 6]])

In [ ]:
#slicing on both rows and column
arr1[0:2, 1:3]

array([[9, 4],
       [9, 6]])

In [ ]:
arr1[0:2, [0, 1]]

array([[8, 9],
       [8, 9]])

In [ ]:
arr1[0, [1,3]]

array([9, 1])

In [ ]:
arr1[2:4, [0, 2]]

array([[8, 1],
       [8, 7]])

In [ ]:
arr1

array([[8, 9, 4, 1, 9, 7],
       [8, 9, 6, 6, 3, 3],
       [8, 2, 1, 6, 6, 5],
       [8, 1, 7, 4, 4, 2],
       [9, 3, 3, 2, 9, 3]])

In [ ]:
arr1[2:5]

array([[8, 2, 1, 6, 6, 5],
       [8, 1, 7, 4, 4, 2],
       [9, 3, 3, 2, 9, 3]])

In [ ]:
arr1[2:5, 0:2] #slicing

array([[8, 2],
       [8, 1],
       [9, 3]])

In [ ]:
arr1[2:5, [0, 2]] 
# 2:5 provides from 2nd row to 5-1=4 , till 4th row
# [0,2] give only 0th and 2nd column values only

array([[8, 1],
       [8, 7],
       [9, 3]])

In [ ]:
arr1[[2,4]] # selecting specific column

array([[8, 2, 1, 6, 6, 5],
       [9, 3, 3, 2, 9, 3]])

In [ ]:
arr1[2 : 4] #slicing

array([[8, 2, 1, 6, 6, 5],
       [8, 1, 7, 4, 4, 2]])

In [ ]:
arr1

array([[8, 9, 4, 1, 9, 7],
       [8, 9, 6, 6, 3, 3],
       [8, 2, 1, 6, 6, 5],
       [8, 1, 7, 4, 4, 2],
       [9, 3, 3, 2, 9, 3]])

In [ ]:
arr1[2:4, [1, 3]]

array([[2, 6],
       [1, 4]])

In [45]:
arr1 = np.random.randint(1, 3, (3,3))
arr2 = np.random.randint(1, 3, (3,3))

In [46]:
arr1

array([[1, 1, 2],
       [2, 2, 1],
       [1, 2, 1]])

In [ ]:
arr2

array([[1, 1, 1],
       [2, 1, 2],
       [2, 2, 2]])

In [ ]:
arr1 + arr2

array([[2, 3, 3],
       [4, 3, 4],
       [4, 3, 4]])

In [ ]:
arr1 - arr2

array([[ 0,  1,  1],
       [ 0,  1,  0],
       [ 0, -1,  0]])

In [ ]:
arr1 * arr2

array([[1, 2, 2],
       [4, 2, 4],
       [4, 2, 4]])

In [47]:
#matrix multiplication

arr1

array([[1, 1, 2],
       [2, 2, 1],
       [1, 2, 1]])

In [ ]:
arr2

array([[1, 1, 1],
       [2, 1, 2],
       [2, 2, 2]])

In [ ]:
arr1 @ arr2 # @ is multiplication symbol in numpy
# row 1 x col1   row 1 x col2   row 1 x col 3
# row 2 x col1   row 2 x col2   row 2 x col 3
# row 3 x col1   row 3 x col2   row 3 x col 3

# when should we multiply matrix?
# if m x n and p x q, if n==p then only multiply matrix

array([[ 9,  7,  9],
       [10,  8, 10],
       [ 8,  7,  8]])

In [ ]:
arr1 / arr2 #index wise divison

array([[1. , 2. , 2. ],
       [1. , 2. , 1. ],
       [1. , 0.5, 1. ]])

In [ ]:
arr1 / 0

C:\Users\ramki\AppData\Local\Temp\ipykernel_18512\824215542.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1 / 0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [ ]:
#Broad casting

In [34]:
arr = np.zeros((3, 4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
arr + 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [36]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [ ]:
a.shape

(4,)

In [ ]:
arr + a # index column wise addition
# Internal working
""" 
[[0., 0., 0., 0.],
 [0., 0., 0., 0.],
 [0., 0., 0., 0.]] + 
[[1, 2, 3, 4],
 [0., 0., 0., 0.],
 [0., 0., 0., 0.]] + 
[[0., 0., 0., 0.],
 [1, 2, 3, 4],
 [0., 0., 0., 0.]] + 
[[0., 0., 0., 0.],
 [0., 0., 0., 0.],
 [1, 2, 3, 4]] 
=
[[1., 2., 3., 4.],
[1., 2., 3., 4.],
[1., 2., 3., 4.]]
"""

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [37]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
a

array([1, 2, 3, 4])

In [24]:
a = np.array([[1, 2, 3]])
a

array([[1, 2, 3]])

In [31]:
arr + a

ValueError: operands could not be broadcast together with shapes (5,) (1,3) 

In [26]:
# Transpose Matrix
# index row wise addition
a.T # a.T , T means transpose

array([[1],
       [2],
       [3]])

In [38]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [39]:
arr + a.T # Transpose Matrix: convert column wise to row wise
# Internally working of Transpose Matrix
""" 
[[0., 0., 0., 0.],
 [0., 0., 0., 0.],
 [0., 0., 0., 0.]] +
[[1],
 [2],
 [3]]
=
[[1, 0., 0., 0.],
 [2, 0., 0., 0.],
 [3, 0., 0., 0.]] +
[[0., 1, 0., 0.],
 [0., 2, 0., 0.],
 [0., 3, 0., 0.]] +
[[0., 0., 1, 0.],
 [0., 0., 2, 0.],
 [0., 0., 3, 0.]] +
[[0., 0., 0., 1],
 [0., 0., 0., 2],
 [0., 0., 0., 3]] 
=
[[1., 1., 1., 1.],
 [2., 2., 2., 2.],
 [3., 3., 3., 3.]]
"""

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [40]:
a.T

array([[1],
       [2],
       [3]])

In [41]:
a = np.array([1, 2, 3])
a.T

array([1, 2, 3])

In [48]:
arr1

array([[1, 1, 2],
       [2, 2, 1],
       [1, 2, 1]])

In [49]:
np.sqrt(arr1)

array([[1.        , 1.        , 1.41421356],
       [1.41421356, 1.41421356, 1.        ],
       [1.        , 1.41421356, 1.        ]])

In [50]:
np.log10(arr1)

array([[0.     , 0.     , 0.30103],
       [0.30103, 0.30103, 0.     ],
       [0.     , 0.30103, 0.     ]])

In [51]:
np.exp(arr1) # exponential is the reverse of logarithmic

array([[2.71828183, 2.71828183, 7.3890561 ],
       [7.3890561 , 7.3890561 , 2.71828183],
       [2.71828183, 7.3890561 , 2.71828183]])

In [52]:
a

array([1, 2, 3])

In [53]:
np.min(a)

1

In [54]:
arr1

array([[1, 1, 2],
       [2, 2, 1],
       [1, 2, 1]])

In [55]:
np.min(arr1)

1

In [56]:
np.max(arr1)

2

In [57]:
arr1

array([[1, 1, 2],
       [2, 2, 1],
       [1, 2, 1]])

In [58]:
arr1.T

array([[1, 2, 1],
       [1, 2, 2],
       [2, 1, 1]])

In [59]:
arr1.flatten() #reduce higher dimension to 1 d

array([1, 1, 2, 2, 2, 1, 1, 2, 1])

In [60]:
#expand_dims >>  expands the array by inserting a new axis
# use case : used in image processing

In [62]:
arr = np.array([[1, 2, 3], [4, 5, 6], [1, 2, 3]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [63]:
np.sum(arr)

27

In [64]:
np.sum(arr, axis=0) # axis=0 means row wise

array([ 6,  9, 12])

In [65]:
np.sum(arr, axis=1) # axis=1 means column wise

array([ 6, 15,  6])

In [66]:
#expand_dims >>expand the dimension of array
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [67]:
arr.ndim

1

In [68]:
arr1 = np.expand_dims(arr, axis = 0)
arr1

array([[1, 2, 3, 4]])

In [69]:
arr1.ndim

2

In [70]:
arr2 = np.expand_dims(arr1, axis = 0)
arr2

array([[[1, 2, 3, 4]]])

In [71]:
arr2.shape

(1, 1, 4)

In [72]:
arr

array([1, 2, 3, 4])

In [73]:
arr1 = np.expand_dims(arr, axis = 1)
arr1

array([[1],
       [2],
       [3],
       [4]])

In [75]:
arr = np.zeros((3, 4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [76]:
arr1 = np.expand_dims(arr, axis = 1)
arr1

# what is expand_dims?
# It expand the dimension by 1 of any array

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [77]:
arr1 = np.expand_dims(arr, axis = 0)
arr1

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
# Application of expand_dims
# 1. increase the image from 2D to 3D in image processing

In [78]:
import numpy as np

# Example matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Using np.dot for matrix multiplication
matrix_product = np.dot(A, B)
print("Matrix product using np.dot:\n", matrix_product)

# Using @ operator for matrix multiplication (Python 3.5 and later)
matrix_product = A @ B
print("Matrix product using @ operator:\n", matrix_product)

Matrix product using np.dot:
 [[19 22]
 [43 50]]
Matrix product using @ operator:
 [[19 22]
 [43 50]]


In [79]:
import numpy as np
import time

# Generate two random NumPy arrays with one million elements each
array1 = np.random.rand(1000000)
array2 = np.random.rand(1000000)

# Measure time for the vectorized version using np.dot
start_time_vectorized = time.time()
result_vectorized = np.dot(array1, array2)
end_time_vectorized = time.time()

# Print the time taken for the vectorized version
print("Time taken for vectorized calculation: " + str(1000 * (end_time_vectorized - start_time_vectorized)) + " milliseconds")

# Reset result_vectorized to 0
result_vectorized = 0

# Measure time for the version using a for loop
start_time_for_loop = time.time()
for index in range(1000000):
    result_vectorized += array1[index] * array2[index]
end_time_for_loop = time.time()

# Print the time taken for the for loop version
print("Time taken for calculation using a for loop: " + str(1000 * (end_time_for_loop - start_time_for_loop)) + " milliseconds")

Time taken for vectorized calculation: 4.535198211669922 milliseconds
Time taken for calculation using a for loop: 633.599042892456 milliseconds


In [80]:
np.array(np.matrix([[1, 2], [5, 6]]))

array([[1, 2],
       [5, 6]])

In [81]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [82]:
np.count_nonzero(arr)

6

In [83]:
import numpy as geek 
  
my_scalar = 12
   
print ("Input  scalar : ", my_scalar) 
    
out_arr = geek.asanyarray(my_scalar)  
print ("output array from input scalar : ", out_arr)  
print(type(out_arr)) 

Input  scalar :  12
output array from input scalar :  12
<class 'numpy.ndarray'>
